permalink: /:categories/:title/

exclude: ["README.md"]
pygments: true
markdown: redcarpet

redcarpet:
  extensions: [tables]
  
excerpt_separator: <!-- more -->
  
title: Leandre `nekuz0r` Gohy
author:
  name: Leandre Gohy
  email: leandre.gohy@hexeo.be
  github: nekuz0r
  twitter: leandregohy
  available_for_hire: false